### ISSUE TITLE
Cannot find train.pickle

### ISSUE THREAD

**Issue by Horizon2333** [dfan/vqa-baseline#1]
Thank you for your contribution.
When I clone your repository and run your code, it shows:

in dataset.py, line68
      feature_file = open('train.pickle', 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'train.pickle'

I cannot find the file "mtrain.pickle" from your repository , maybe you forget to upload them?

**Comment by dfan** [comment]
You can generate this by running an image encoder (say ImageNet pretrained ResNet) over the images and saving the 2048-dimensional feature vectors into a pickled dictionary.

This code was for a class assignment so I will not add the feature file to the repository
